# Generated by Django 4.1.1 on 2022-09-22 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_uncompletedcourse_name_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='completedcourse',
            name='name_course',
        ),
        migrations.RemoveField(
            model_name='uncompletedcourse',
            name='name_course',
        ),
        migrations.AddField(
            model_name='completedcourse',
            name='comp_course',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='uncompletedcourse',
            name='uncomp_course',
            field=models.TextField(null=True),
        ),
    ]
